#!/bin/sh

# Build the dependency extractor plugin
./gradlew :plugin:build

# Invoke a build extracting the GitHub Dependency Graph
./gradlew --no-configuration-cache --no-build-cache -I plugin-self-test.init.gradle --no-scan --console=plain $1

# Submit the dependency graph to GitHub
curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GITHUB_TOKEN"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/gradle/github-dependency-extractor/dependency-graph/snapshots \
  -d @build/reports/github-dependency-report/github-dependency-manifest.json
