#!/bin/sh

# Build and publish the dependency graph plugin
./gradlew :plugin:publishPluginMavenPublicationToLocalPluginsRepository

# Invoke a build extracting the GitHub Dependency Graph
./gradlew --no-configuration-cache --no-build-cache -I plugin-self-test.init.gradle $*

if [[ -z "${GITHUB_TOKEN}" ]]; then
  echo "GITHUB_TOKEN must be set in order to submit dependency graph"
else
  # Submit the dependency graph to GitHub
  curl -L \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_TOKEN"\
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/repos/gradle/dependency-graph-gradle-plugin/dependency-graph/snapshots \
    -d @build/reports/dependency-graph-snapshots/plugin-self-test.json
fi
