#!/bin/sh

export GITHUB_JOB_ID="42"
export GITHUB_JOB_CORRELATOR="plugin-self-test"
export GITHUB_REF="refs/heads/main"
export GITHUB_SHA=$( git rev-parse HEAD )
export GITHUB_WORKSPACE=$( pwd )

./plugin-self-test $*
