#!/bin/sh

export GITHUB_DEPENDENCY_GRAPH_JOB_ID="42"
export GITHUB_DEPENDENCY_GRAPH_JOB_CORRELATOR="plugin-self-test"
export GITHUB_DEPENDENCY_GRAPH_REF="refs/heads/main"
export GITHUB_DEPENDENCY_GRAPH_SHA=$( git rev-parse HEAD )
export GITHUB_DEPENDENCY_GRAPH_WORKSPACE=$( pwd )

./plugin-self-test $*
